# Global configuration
global:
  scrape_interval: 60s # Set the scrape interval to every 60 seconds. Default is every 1 minute.
  evaluation_interval: 60s # Evaluate rules every 60 seconds. The default is every 1 minute.
  scrape_timeout: 10s # scrape_timeout is set to the global default (10s).

# Scrape configs
scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"] # Assuming Prometheus is running on localhost:9091

  # Scrape Loki metrics
  - job_name: "loki"
    metrics_path: "/metrics" # Loki's metrics endpoint
    static_configs:
      - targets: ["localhost:3100"] # Assuming Loki is running on localhost:3101

  # Scrape the application
  - job_name: "my_app"
    metrics_path: "/api/v1/metrics" # app's metrics endpoint
    static_configs:
      - targets: ["host.docker.internal:8080"] # Assuming the app is running on host.docker.internal:8080
